export const Routes = {
  Home: 'Home',
  Profile: 'Profile',
  MyAccount: 'MyAccount',
  Cart: 'Cart',
  Products: 'Products',
  Orders: 'Orders',
  // LoginEmail: 'LoginEmail',
  EmailEntry: 'EmailEntry',
  PasswordEntry: 'PasswordEntry',
  Mobilelogin: 'Mobilelogin',
  OtpScreen: 'OtpScreen',
  ProductDetail: 'ProductDetail',
  Signup: 'Signup',
};
