export const Routes = {
  Home: 'Home',
  Profile: 'Profile',
  MyAccount: 'MyAccount',
  Cart: 'Cart',
  Wishlist: 'Wishlist',
  Products: 'Products',
  Orders: 'Orders',
  // LoginEmail: 'LoginEmail',
  EmailEntry: 'EmailEntry',
  PasswordEntry: 'PasswordEntry',
  Mobilelogin: 'Mobilelogin',
  EmailOtpScreen: 'EmailOtpScreen',
  EmailOtpVerification: 'EmailOtpVerification',
  OtpScreen: 'OtpScreen',
  ProductDetail: 'ProductDetail',
  Checkoutform: 'Checkoutform',
  Signup: 'Signup',
  SignupEmail: 'SignupEmail',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  SavedAddress: 'SavedAddress',
  OrderPlaced: 'OrderPlaced',
  OrderTracking: 'OrderTracking',
  BellNotification: 'BellNotification',
  ChangePassword:'ChangePassword',
  // static pages
  Contact: 'Contact',
};
