import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/Scaling';
import getFontFamily from '../../assets/fonts/helper';

export const CartStyle = StyleSheet.create({
  userNoLoggedIn: {
    backgroundColor: '#fff',
    padding: horizontalScale(15),
    borderWidth: horizontalScale(0.5),
    borderColor: '#ccc',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: horizontalScale(10),
    borderRadius: horizontalScale(20),
  },
  mainBtn: {
    width: '100%',
    padding: horizontalScale(10),
    backgroundColor: '#f9b000',
    marginVertical: verticalScale(20),
    borderRadius: horizontalScale(10),
    alignItems: 'center',
  },
  mainBtnText: {
    color: '#fff',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(16),
    textTransform: 'uppercase',
    fontFamily: getFontFamily('Roboto', 700),
    letterSpacing: horizontalScale(0.5),
  },
  describe: {
    color: '#6c6b6b',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14),
    fontFamily: getFontFamily('Roboto', 600),
    letterSpacing: horizontalScale(0.2),
    marginTop: verticalScale(3),
  },
  CountCart: {
    position: 'absolute',
    top: -5,
    right: -10,
    backgroundColor: '#f35c6e',
    paddingHorizontal: horizontalScale(5),
    paddingVertical: verticalScale(1),
    borderRadius: horizontalScale(10),
  },
  cartProd: {
    height: verticalScale(60),
    width: horizontalScale(60),
  },
  cartAddPrice: {
    display: 'flex',
    alignItems: 'center',
    columnGap: horizontalScale(7),
    flexDirection: 'row',
    marginTop: verticalScale(10),
  },
  cuttedPrice: {
    fontSize: scaleFontSize(11),
    textDecorationLine: 'line-through',
    color: '#000',
  },
  price: {
    fontSize: scaleFontSize(11),
    color: '#000',
    fontWeight: 500,
  },
  cartTrash: {
    borderWidth: 0.5,
    borderColor: '#8dc6ff',
    height: verticalScale(25),
    padding: horizontalScale(5),
    width: horizontalScale(27),
    borderRadius: horizontalScale(4),
    backgroundColor: '#e4f1fe',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemCount: {
    borderWidth: 0.5,
    borderColor: '#8dc6ff',
    height: verticalScale(25),
    width: horizontalScale(40),
    padding: horizontalScale(5),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: horizontalScale(4),
    backgroundColor: '#fff',
  },
  itemTotalAmount: {
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(18),
    fontWeight: 800,
  },
  ttlAmt: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(5),
  },
  ttlAmtText: {
    fontSize: scaleFontSize(13.5),
    lineHeight: verticalScale(15),
    fontFamily: getFontFamily('Robotos', 500),
  },
  borderTop: {
    borderTopWidth: 0.4,
    borderColor: '#ccc',
  },
  gstText: {
    fontSize: scaleFontSize(11.5),
    lineHeight: verticalScale(13.5),
  },
  stickyCheckoutContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingVertical: verticalScale(6),
    paddingHorizontal: horizontalScale(20),
    columnGap: horizontalScale(10),
  },
  shadowProp: {
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: -4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  checkoutText: {
    color: '#000',
    opacity: 0.8,
    fontWeight: '500',
    fontSize: scaleFontSize(11),
    lineHeight: verticalScale(14),
  },
  CheckoutBtn: {
    backgroundColor: '#f9b000',
    width: horizontalScale(190),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: horizontalScale(8),
    borderRadius: horizontalScale(6),
    paddingVertical: verticalScale(16),
  },
  checkoutBtnText: {
    color: '#fff',
    fontSize: scaleFontSize(14),
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: horizontalScale(15),
    borderTopLeftRadius: horizontalScale(20),
    borderTopRightRadius: horizontalScale(20),
  },
  removeFromCart: {
    borderWidth: 1,
    borderRadius: horizontalScale(13),
    borderColor: '#ccc',
    padding: horizontalScale(13),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: horizontalScale(12),
  },
  removeCartBtn: {
    backgroundColor: '#efe4c6',
    height: verticalScale(35),
    borderRadius: horizontalScale(10),
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: horizontalScale(8),
    paddingVertical: verticalScale(10),
  },
  removeFromCartText: {
    color: '#f9b000',
    fontSize: scaleFontSize(13),
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  wishlistBtn: {
    backgroundColor: '#f9b000',
    height: verticalScale(35),
    borderRadius: horizontalScale(10),
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: horizontalScale(8),
    paddingVertical: verticalScale(10),
  },
  wishlistBtnText: {
    color: '#fff',
    fontSize: scaleFontSize(13),
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  modalImage: {
    height: verticalScale(60),
    width: horizontalScale(60),
    borderRadius: horizontalScale(13),
  },
});
