export const SEND_ORDER_NOTIFICATION_REQUEST =
  'SEND_ORDER_NOTIFICATION_REQUEST';
export const SEND_ORDER_NOTIFICATION_SUCCESS =
  'SEND_ORDER_NOTIFICATION_SUCCESS';
export const SEND_ORDER_NOTIFICATION_FAIL = 'SEND_ORDER_NOTIFICATION_FAIL';
