export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

// otp constants

export const SEND_MOBILE_OTP_REQUEST = 'SEND_MOBILE_OTP_REQUEST';
export const SEND_MOBILE_OTP_SUCCESS = 'SEND_MOBILE_OTP_SUCCESS';
export const SEND_MOBILE_OTP_FAIL = 'SEND_MOBILE_OTP_FAIL';

export const VERIFY_MOBILE_OTP_REQUEST = 'VERIFY_MOBILE_OTP_REQUEST';
export const VERIFY_MOBILE_OTP_SUCCESS = 'VERIFY_MOBILE_OTP_SUCCESS';
export const VERIFY_MOBILE_OTP_FAIL = 'VERIFY_MOBILE_OTP_FAIL';

export const SEND_EMAIL_OTP_REQUEST = 'SEND_EMAIL_OTP_REQUEST';
export const SEND_EMAIL_OTP_SUCCESS = 'SEND_EMAIL_OTP_SUCCESS';
export const SEND_EMAIL_OTP_FAIL = 'SEND_EMAIL_OTP_FAIL';

export const VERIFY_EMAIL_OTP_REQUEST = 'VERIFY_EMAIL_OTP_REQUEST';
export const VERIFY_EMAIL_OTP_SUCCESS = 'VERIFY_EMAIL_OTP_SUCCESS';
export const VERIFY_EMAIL_OTP_FAIL = 'VERIFY_EMAIL_OTP_FAIL';

export const VERIFY_EMAIL_OTP_FORGOT_REQUEST =
  'VERIFY_EMAIL_OTP_FORGOT_REQUEST';
export const VERIFY_EMAIL_OTP_FORGOT_SUCCESS =
  'VERIFY_EMAIL_OTP_FORGOT_SUCCESS';
export const VERIFY_EMAIL_OTP_FORGOT_FAIL = 'VERIFY_EMAIL_OTP_FORGOT_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const CLEAR_UPDATE_USER_ERRORS = 'CLEAR_UPDATE_USER_ERRORS';

export const ADD_SHIPPING_INFO_REQUEST = 'ADD_SHIPPING_INFO_REQUEST';
export const ADD_SHIPPING_INFO_SUCCESS = 'ADD_SHIPPING_INFO_SUCCESS';
export const ADD_SHIPPING_INFO_FAIL = 'ADD_SHIPPING_INFO_FAIL';

export const GET_SHIPPING_INFO_REQUEST = 'GET_SHIPPING_INFO_REQUEST';
export const GET_SHIPPING_INFO_SUCCESS = 'GET_SHIPPING_INFO_SUCCESS';
export const GET_SHIPPING_INFO_FAIL = 'GET_SHIPPING_INFO_FAIL';

export const UPDATE_SHIPPING_INFO_REQUEST = 'UPDATE_SHIPPING_INFO_REQUEST';
export const UPDATE_SHIPPING_INFO_SUCCESS = 'UPDATE_SHIPPING_INFO_SUCCESS';
export const UPDATE_SHIPPING_INFO_FAIL = 'UPDATE_SHIPPING_INFO_FAIL';

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
